isis_adj_eg={
    'version': '1.0.0',
    'instanceId': '----',
    'eventId': 'NETWORK-NETWORKS-2-258',
    'namespace': 'ASSURANCE',
    'name': None,
    'description': None,
    'type': 'NETWORK',
    'category': 'ERROR',
    'domain': 'Know Your Network',
    'subDomain': 'Networks',
    'severity': 2,
    'source': 'ndp',
    'timestamp': 1620488117827,
    'details': {
        'Type': 'Network Device',
        'Assurance Issue Priority': 'P2',
        'Assurance Issue Details': 'ISIS adjacency failed test ',
        'Device': '10.50.30.6',
        'Assurance Issue Name': 'ISIS Adjacency Failed test',
        'Assurance Issue Category': 'connectivity',
        'Assurance Issue Status': 'active'
    },
    'ciscoDnaEventLink': 'https: //dna.example.com/dna/assurance/issueDetails?issueId=12342345-2342423-4223-234235-23423423',
    'note': 'To programmatically get more info see here - https://<ip-address>/dna/platform/app/consumer-portal/developer-toolkit/apis?apiId=8684-39bb-4e89-a6e4',
    'context': None,
    'userId': None,
    'i18n': None,
    'eventHierarchy': None,
    'message': None,
    'messageParams': None,
    'parentInstanceId': None,
    'network': None
}
